### ISSUE TITLE
Feature: standard `/poll` vote emojis for server

### ISSUE THREAD

**Issue by gerdoe-jr** [Lohkdesgds/Bread#1]
I.e `/configuration poll emojis ...`

**Comment by Lohkdesgds** [comment]
Added this right here @ https://github.com/Lohkdesgds/Bread/commit/795d5d72d1862e8c2878062d1e1d4840d7d77570
https://github.com/Lohkdesgds/Bread/blob/eff1bf67339e6cb28ea45aa37ca85718b6fef680/src/commands/configurar.cpp#L65-L80

The command is `/configuration poll-defaults emojis: ...` (en.US)
